#!/bin/bash
# sync-claude-context.sh
# Syncs context files across Claude Code, Cowork, and Claude.ai
#
# Usage: ./sync-claude-context.sh
#
# Source of truth: this repo (shared/ + private/)
# Targets:
#   - ~/CoworkSpace/          (Cowork reads .md files from working folder)
#   - ~/.claude/CLAUDE.md     (Claude Code global instructions)
#   - Prints reminder for Claude.ai memory edits (manual step)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Source .env for persistent configuration (COWORK_DIR, SKILLS_DIR, etc.)
if [ -f "$SCRIPT_DIR/.env" ]; then
    # shellcheck source=/dev/null
    source "$SCRIPT_DIR/.env"
fi

SHARED_DIR="$SCRIPT_DIR/shared"
PRIVATE_DIR="$SCRIPT_DIR/private"
COWORK_DIR="${COWORK_DIR:-$HOME/CoworkSpace}"
SKILLS_DIR="${SKILLS_DIR:-}"
CLAUDE_CODE_MD="$HOME/.claude/CLAUDE.md"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo "=== Claude Context Sync ==="
echo ""

# Check private/ exists
HAS_PRIVATE=true
if [ ! -d "$PRIVATE_DIR" ] || [ -z "$(ls -A "$PRIVATE_DIR" 2>/dev/null)" ]; then
    HAS_PRIVATE=false
    echo -e "${YELLOW}No private/ directory found. Run ./setup.sh first to create personal config.${NC}"
    echo -e "${YELLOW}Syncing shared files only.${NC}"
    echo ""
fi

# 1. Sync to Cowork (symlinks)
echo -e "${GREEN}[1/4] Syncing to Cowork...${NC}"
mkdir -p "$COWORK_DIR"

# Shared files
for file in "$SHARED_DIR"/*.md; do
    [ -f "$file" ] || continue
    filename="$(basename "$file")"
    rm -f "$COWORK_DIR/$filename"
    ln -s "$file" "$COWORK_DIR/$filename"
    echo "  Linked: shared/$filename -> CoworkSpace/"
done

# Private files
if [ "$HAS_PRIVATE" = true ]; then
    for file in "$PRIVATE_DIR"/*.md; do
        [ -f "$file" ] || continue
        filename="$(basename "$file")"
        rm -f "$COWORK_DIR/$filename"
        ln -s "$file" "$COWORK_DIR/$filename"
        echo "  Linked: private/$filename -> CoworkSpace/"
    done
fi

# Create Cowork subfolders
for dir in payments reports proposals candidates meeting-notes invoices; do
    mkdir -p "$COWORK_DIR/$dir"
done
echo "  Created subfolder structure in CoworkSpace/"

# 2. Sync skills to ~/.claude/skills/ (if SKILLS_DIR is configured)
echo ""
if [ -n "$SKILLS_DIR" ] && [ -d "$SKILLS_DIR" ]; then
    echo -e "${GREEN}[2/4] Syncing skills from $SKILLS_DIR...${NC}"
    mkdir -p "$HOME/.claude/skills"
    for skill_dir in "$SKILLS_DIR"/*/; do
        [ -f "$skill_dir/SKILL.md" ] || continue
        skill_name="$(basename "$skill_dir")"
        target="$HOME/.claude/skills/$skill_name"

        # Skip if target exists and isn't one of our symlinks
        if [ -e "$target" ] || [ -L "$target" ]; then
            existing_link=$(readlink "$target" 2>/dev/null || echo "")
            case "$existing_link" in
                "$SKILLS_DIR"/*)
                    # Our symlink from a previous sync, safe to replace
                    rm -f "$target"
                    ;;
                "")
                    # Real directory, not a symlink
                    echo -e "  ${YELLOW}Skipped: $skill_name (real directory exists, not overwriting)${NC}"
                    continue
                    ;;
                *)
                    # Symlink to somewhere else (plugin marketplace, manual install)
                    echo -e "  ${YELLOW}Skipped: $skill_name (symlink to $existing_link, not overwriting)${NC}"
                    continue
                    ;;
            esac
        fi

        ln -s "$skill_dir" "$target"
        echo "  Linked: $skill_name -> ~/.claude/skills/"
    done
else
    echo -e "${YELLOW}[2/4] Skills sync skipped (SKILLS_DIR not set in .env)${NC}"
fi

# 3. Build Claude Code CLAUDE.md
echo ""
echo -e "${GREEN}[3/4] Building Claude Code CLAUDE.md...${NC}"
mkdir -p "$HOME/.claude"

BEGIN_MARKER="# --- BEGIN claude-context (auto-generated, do not edit) ---"
END_MARKER="# --- END claude-context ---"

# Generate our content into a temp file
GENERATED=$(mktemp)
{
    # Shared files first
    for file in "$SHARED_DIR"/*.md; do
        [ -f "$file" ] || continue
        echo "---"
        echo ""
        cat "$file"
        echo ""
    done

    # Private files second
    if [ "$HAS_PRIVATE" = true ]; then
        for file in "$PRIVATE_DIR"/*.md; do
            [ -f "$file" ] || continue
            echo "---"
            echo ""
            cat "$file"
            echo ""
        done
    fi
} > "$GENERATED"

# Migrate from old format: if file starts with our old header, it's entirely ours
if [ -f "$CLAUDE_CODE_MD" ] && head -1 "$CLAUDE_CODE_MD" | grep -q "Auto-generated by sync-claude-context.sh"; then
    echo -e "  ${YELLOW}Migrating from old format (full overwrite -> marker-based)${NC}"
    {
        echo "$BEGIN_MARKER"
        cat "$GENERATED"
        echo "$END_MARKER"
    } > "$CLAUDE_CODE_MD"
    rm -f "$GENERATED"
    echo "  Written: ~/.claude/CLAUDE.md ($(wc -l < "$CLAUDE_CODE_MD") lines)"
    SKIP_BUILD=true
fi

# If CLAUDE.md exists and has user content, check for duplicate H2 sections
if [ "${SKIP_BUILD:-}" != "true" ] && [ -f "$CLAUDE_CODE_MD" ]; then
    # Extract user's H2 headers (outside our markers)
    USER_CONTENT=$(mktemp)
    if grep -qF "$BEGIN_MARKER" "$CLAUDE_CODE_MD"; then
        # Get content outside our markers (awk for literal string matching)
        awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
            $0 == begin { inside=1; next }
            $0 == end { inside=0; next }
            !inside { print }
        ' "$CLAUDE_CODE_MD" > "$USER_CONTENT"
    else
        cp "$CLAUDE_CODE_MD" "$USER_CONTENT"
    fi

    # Find H2 headers the user already has
    USER_H2S=$(grep -E '^## ' "$USER_CONTENT" 2>/dev/null | sed 's/^## //' || true)

    if [ -n "$USER_H2S" ]; then
        # Filter out sections from our content that the user already has
        FILTERED=$(mktemp)
        python3 -c "
import sys

user_h2s = set()
for line in '''${USER_H2S}'''.strip().split('\n'):
    h = line.strip()
    if h:
        user_h2s.add(h)

with open('$GENERATED') as f:
    lines = f.readlines()

filtered = []
skipping = False
skipped = []

for line in lines:
    stripped = line.rstrip('\n')
    if stripped.startswith('## '):
        header = stripped[3:]
        if header in user_h2s:
            skipping = True
            skipped.append(header)
            continue
        else:
            skipping = False
    elif stripped.startswith('# ') and not stripped.startswith('## '):
        skipping = False

    if not skipping:
        filtered.append(line)

with open('$FILTERED', 'w') as f:
    f.writelines(filtered)

for s in skipped:
    print(s, file=sys.stderr)
" 2>"${FILTERED}.skipped"

        SKIP_LIST=$(cat "${FILTERED}.skipped" 2>/dev/null)
        if [ -n "$SKIP_LIST" ]; then
            echo -e "  ${YELLOW}Skipped (already in your CLAUDE.md):${NC}"
            while IFS= read -r h; do
                echo "    - ## $h"
            done <<< "$SKIP_LIST"
        fi

        mv "$FILTERED" "$GENERATED"
        rm -f "${FILTERED}.skipped"
    fi
    rm -f "$USER_CONTENT"
fi

# Build the final file with markers
if [ "${SKIP_BUILD:-}" = "true" ]; then
    : # Already handled by migration above
elif [ -f "$CLAUDE_CODE_MD" ] && grep -qF "$BEGIN_MARKER" "$CLAUDE_CODE_MD"; then
    # Replace content between markers, keep everything else
    TMPFILE=$(mktemp)
    awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v content="$GENERATED" '
        $0 == begin { print; while ((getline line < content) > 0) print line; skip=1; next }
        $0 == end { skip=0; print; next }
        !skip { print }
    ' "$CLAUDE_CODE_MD" > "$TMPFILE"
    mv "$TMPFILE" "$CLAUDE_CODE_MD"
elif [ -f "$CLAUDE_CODE_MD" ]; then
    # First time: append our block to existing file
    {
        echo ""
        echo "$BEGIN_MARKER"
        cat "$GENERATED"
        echo "$END_MARKER"
    } >> "$CLAUDE_CODE_MD"
else
    # No existing file: create fresh
    {
        echo "$BEGIN_MARKER"
        cat "$GENERATED"
        echo "$END_MARKER"
    } > "$CLAUDE_CODE_MD"
fi

rm -f "$GENERATED" 2>/dev/null
if [ "${SKIP_BUILD:-}" != "true" ]; then
    echo "  Written: ~/.claude/CLAUDE.md ($(wc -l < "$CLAUDE_CODE_MD") lines)"
fi

# 4. Reminder for Claude.ai
echo ""
echo -e "${GREEN}[4/4] Claude.ai Chat sync${NC}"
echo -e "${YELLOW}  Manual step required:${NC}"
echo "  Claude.ai uses server-side memory, not local files."
echo "  When you change context files, update memory edits in Chat:"
echo "    1. Open claude.ai"
echo "    2. Ask: 'view my memory edits'"
echo "    3. Update any stale entries to match your source files"
echo ""

# 4. Git status check
if [ -d "$SCRIPT_DIR/.git" ]; then
    echo -e "${GREEN}[bonus] Git status:${NC}"
    cd "$SCRIPT_DIR"
    if [ -n "$(git status --porcelain)" ]; then
        echo "  Uncommitted changes detected. Run:"
        echo "    cd $SCRIPT_DIR && git add -A && git commit -m 'update context' && git push"
    else
        echo "  All clean. No uncommitted changes."
    fi
fi

echo ""
echo -e "${GREEN}Done.${NC} Context synced to Cowork + Claude Code."
