#!/bin/bash
# sync-claude-context.sh
# Syncs context files across Claude Code, Cowork, and Claude.ai
#
# Usage: ./sync-claude-context.sh
#
# Source of truth: this repo (shared/ + private/)
# Targets:
#   - ~/CoworkSpace/          (Cowork reads .md files from working folder)
#   - ~/.claude/CLAUDE.md     (Claude Code global instructions)
#   - Prints reminder for Claude.ai memory edits (manual step)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SHARED_DIR="$SCRIPT_DIR/shared"
PRIVATE_DIR="$SCRIPT_DIR/private"
COWORK_DIR="${COWORK_DIR:-$HOME/CoworkSpace}"
CLAUDE_CODE_MD="$HOME/.claude/CLAUDE.md"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo "=== Claude Context Sync ==="
echo ""

# Check private/ exists
HAS_PRIVATE=true
if [ ! -d "$PRIVATE_DIR" ] || [ -z "$(ls -A "$PRIVATE_DIR" 2>/dev/null)" ]; then
    HAS_PRIVATE=false
    echo -e "${YELLOW}No private/ directory found. Run ./setup.sh first to create personal config.${NC}"
    echo -e "${YELLOW}Syncing shared files only.${NC}"
    echo ""
fi

# 1. Sync to Cowork (symlinks)
echo -e "${GREEN}[1/3] Syncing to Cowork...${NC}"
mkdir -p "$COWORK_DIR"

# Shared files
for file in "$SHARED_DIR"/*.md; do
    [ -f "$file" ] || continue
    filename="$(basename "$file")"
    rm -f "$COWORK_DIR/$filename"
    ln -s "$file" "$COWORK_DIR/$filename"
    echo "  Linked: shared/$filename -> CoworkSpace/"
done

# Private files
if [ "$HAS_PRIVATE" = true ]; then
    for file in "$PRIVATE_DIR"/*.md; do
        [ -f "$file" ] || continue
        filename="$(basename "$file")"
        rm -f "$COWORK_DIR/$filename"
        ln -s "$file" "$COWORK_DIR/$filename"
        echo "  Linked: private/$filename -> CoworkSpace/"
    done
fi

# Create Cowork subfolders
for dir in payments reports proposals candidates meeting-notes invoices; do
    mkdir -p "$COWORK_DIR/$dir"
done
echo "  Created subfolder structure in CoworkSpace/"

# 2. Build Claude Code CLAUDE.md
echo ""
echo -e "${GREEN}[2/3] Building Claude Code CLAUDE.md...${NC}"
mkdir -p "$HOME/.claude"

# Backup existing CLAUDE.md if it wasn't generated by this script
if [ -f "$CLAUDE_CODE_MD" ] && ! grep -q "Auto-generated by sync-claude-context.sh" "$CLAUDE_CODE_MD"; then
    cp "$CLAUDE_CODE_MD" "$CLAUDE_CODE_MD.backup.$(date +%Y%m%d%H%M%S)"
    echo -e "  ${YELLOW}Backed up existing CLAUDE.md (was not generated by this script)${NC}"
fi

{
    echo "# Auto-generated by sync-claude-context.sh"
    echo "# Source: $(basename "$SCRIPT_DIR")/"
    echo "# Do not edit directly. Edit source files and re-run sync."
    echo ""

    # Shared files first
    for file in "$SHARED_DIR"/*.md; do
        [ -f "$file" ] || continue
        echo "---"
        echo ""
        cat "$file"
        echo ""
    done

    # Private files second
    if [ "$HAS_PRIVATE" = true ]; then
        for file in "$PRIVATE_DIR"/*.md; do
            [ -f "$file" ] || continue
            echo "---"
            echo ""
            cat "$file"
            echo ""
        done
    fi
} > "$CLAUDE_CODE_MD"

echo "  Written: ~/.claude/CLAUDE.md ($(wc -l < "$CLAUDE_CODE_MD") lines)"

# 3. Reminder for Claude.ai
echo ""
echo -e "${GREEN}[3/3] Claude.ai Chat sync${NC}"
echo -e "${YELLOW}  Manual step required:${NC}"
echo "  Claude.ai uses server-side memory, not local files."
echo "  When you change context files, update memory edits in Chat:"
echo "    1. Open claude.ai"
echo "    2. Ask: 'view my memory edits'"
echo "    3. Update any stale entries to match your source files"
echo ""

# 4. Git status check
if [ -d "$SCRIPT_DIR/.git" ]; then
    echo -e "${GREEN}[bonus] Git status:${NC}"
    cd "$SCRIPT_DIR"
    if [ -n "$(git status --porcelain)" ]; then
        echo "  Uncommitted changes detected. Run:"
        echo "    cd $SCRIPT_DIR && git add -A && git commit -m 'update context' && git push"
    else
        echo "  All clean. No uncommitted changes."
    fi
fi

echo ""
echo -e "${GREEN}Done.${NC} Context synced to Cowork + Claude Code."
